modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/Influenze0/Enhanced-Block-Entities-NEOFORGED"

[[mods]]
modId="enhancedblockentities"
version="${mod_version}"
displayName="${mod_name}"

displayURL="https://github.com/Influenze0/Enhanced-Block-Entities-NEOFORGED"
logoFile="assets/enhancedblockentities/icon.png"

authors="FoundationGames, 1Influence [NeoForge Port]"

description='''
This mod is an unofficial fork of Enhanced Block Entities for the previously unsupported modloader Neoforge. Optimize and customize block entity rendering using a more modern approach.
'''

[[mixins]]
config="enhancedblockentities.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
